### ISSUE TITLE
Would be nice to have Square API integrated

### ISSUE THREAD

**Issue by bcackerman** [Shopify/active_merchant#1162]

**Comment by bcackerman** [comment]
Any push from others?

**Comment by ntalbott** [comment]
@bcackerman we'd welcome a PR - thanks!

**Comment by kieranklaassen** [comment]
Since Square opened up their API 2 days ago I give a +1

**Comment by aksh0925** [comment]
+1

**Comment by sejalgupta3** [comment]
+1

**Comment by nicklandgrebe** [comment]
+1

**Comment by pelletencate** [comment]
+1, this would be awesome to have!

**Comment by stacybchapman** [comment]
+1 We would love to have this as well!!

**Comment by hadees** [comment]
[Looks like square was already doing it themselves](https://github.com/square/plastic).  I wonder why they won't release the code.

**Comment by jawspeak** [comment]
See this PR for a working implementation: https://github.com/activemerchant/active_merchant/pull/2242

**Comment by frojasg** [comment]
We just published a gem to extend `active_merchant` to have Square API integrated. [Check it out!](https://rubygems.org/gems/active_merchant_square)

**Comment by hossamhossny** [comment]
Last thing I know about the lack of support to Square is that it was because Square API doesn't allow PAN processing, has this changed?
