### ISSUE TITLE
"insurance_total" option within paypal_exrepss_gateway is not working

### ISSUE THREAD

**Issue by kevin-jj** [Shopify/active_merchant#1498]
I have correctly setup the amout of "insurance_total" within PaypalExpressGateway but it can not be able to appear in the order summary at PayPal site.

activemerchant 1.45.0

![screen shot 2014-12-20 at 22 58 11](https://cloud.githubusercontent.com/assets/120368/5515192/be5c7c5e-889b-11e4-99d2-7ba14fc355fd.png)

**Comment by kevin-jj** [comment]
any update?

**Comment by j-mutter** [comment]
Everything looks fine in AM. I wrote this remote test:
```ruby
# in test/remote/gateways/remote_paypal_express_test.rb

  def test_insurance_total
    @options.update(
      :insurance_total => 1,
      :subtotal => 5,
      :tax => 5,
      :shipping => 5,
      :handling => 5
    )

    response = @gateway.setup_purchase(21, @options)

    assert response.success?
  end
```

Which passes no problem:
```bash
$ BUNDLE_GEMFILE=Gemfile_rails40 bundle exec ruby -I"lib:test" test/remote/gateways/remote_paypal_express_test.rb -n /insurance/
Run options: -n /insurance/

# Running tests:

Finished tests in 0.810549s, 1.2337 tests/s, 1.2337 assertions/s.
```

Are you sure that the order you're looking at in PayPal had a non-zero insurance amount?

**Comment by kevin-jj** [comment]
Yes, the soap response from PayPal had a non-zero insurance amount but it did not appear in the order summary as it redirect to the PayPal site.

**Comment by kevin-jj** [comment]
The PayPal Developer Team tested it and told me that  if I use n2 namespace xml structure I have to place 
```xml
<n2:InsuranceTotal currencyID="USD">1.99</n2:InsuranceTotal> 
```
behind the 

```xml
<n2:PaymentDetailsItem> 
```

**Comment by j-mutter** [comment]
The `InsuranceTotal` tag is within `PaymentDetails`, and outside of any `PaymentDetailsItem`s from what I can see: 
```xml
      <n2:PaymentDetails>
        <n2:OrderTotal currencyID='USD'>0.10</n2:OrderTotal>
        <n2:InsuranceTotal currencyID='USD'>0.10</n2:InsuranceTotal>
        <n2:ButtonSource>ActiveMerchant</n2:ButtonSource>
        <n2:PaymentAction>Sale</n2:PaymentAction>
      </n2:PaymentDetails>
```

If the insurance total is in the response from PayPal, everything is working as expected on the AM side. I have no idea why it wouldn't be showing up in the web UI on their end.

@ntalbott @girasquid any ideas? Sounds like everything is ok to me ¯\(°_o)/¯

**Comment by girasquid** [comment]
Is there any extra setup involved on the PayPal side? I'm drawing a blank.

**Comment by kevin-jj** [comment]
Is Shopify Developer Team going to fix this bug?

**Comment by ntalbott** [comment]
@kevin-jj this is not a feature that any of the maintainers use, but if you can create a Pull Request that fixes it with a test that shows the problem and fix, we'd be happy to consider merging it.

Going to close this for now; please open a PR if you find a fix.
