### ISSUE TITLE
Drop Ruby 1.9.3

### ISSUE THREAD

**Issue by j-mutter** [Shopify/active_merchant#1519]
Ruby 1.9.3 is EOL'd and is being dropped entirely on 23 Feb, 2015.

I propose we cut one more minor release of ActiveMerchant that supports 1.9, then move onto Ruby 2+ (or even 2.1+) only.

See https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

@girasquid @ntalbott @wvanbergen

**Comment by wvanbergen** [comment]
I'd say let's keep testing against it until the Feb 23rd, do a minor release, and remove it afterwards from the build matrix.

**Comment by ntalbott** [comment]
:+1:

**Comment by j-mutter** [comment]
Sorry, yeah, I meant on the 23rd. Just wanted to make a record of this so we don't forget.

**Comment by ntalbott** [comment]
@j-mutter @wvanbergen can ya'll make this happen now?

**Comment by j-mutter** [comment]
Awwww yissssss. I'll handle it

**Comment by wvanbergen** [comment]
:fire:

**Comment by wvanbergen** [comment]
I guess this is done now :+1:
