### ISSUE TITLE
Current status of Automated Recurring Billing for new Gateways?

### ISSUE THREAD

**Issue by BaconSoap** [Shopify/active_merchant#1528]
What's the current status of automatic recurring billing? I noticed that the existing gateways have those features marked as deprecated.

#1178 refers to there potentially being separate gems to handle recurring. Do you have any knowledge of existing gems or strategies to handle this? We're working on a project to add a new gateway that has some recurring functionality that we need internally, but would be happy to keep that separate to meet project guidelines so that we can still merge our base changes upstream.

**Comment by ntalbott** [comment]
@BaconSoap as far as I know no one has taken on creating any gems for automated recurring functionality. We definitely consider it to be out of scope for ActiveMerchant.
