### ISSUE TITLE
Paymill transaction in spree ends up with empty card_owner

### ISSUE THREAD

**Issue by jungbunzlav** [Shopify/active_merchant#1538]
I am using the paymill gateway in correlation with spree commerce. My paymill account is currently running in test mode.

Transactions will show up in the paymill backoffice whereas the card owner name is missing.

The corresponding spree log entry states that the ActiveMerchant::Billing::Response lacks the parameter card_owner.

ruby 2.2
activemerchant 1.44.1
activesupport 4.1.8
nokogiri 1.6.5
spree 2.4.2

**Comment by girasquid** [comment]
Looking through `ActiveMerchant::Billing::Response`, it doesn't look like it ever stores the card owner - does Paymill return that in their responses? That seems like something that you would be able to store *before* the transaction gets sent to Paymill.

**Comment by jungbunzlav** [comment]
https://github.com/Shopify/active_merchant/blob/master/lib/active_merchant/billing/gateways/paymill.rb#L55-L60

The code above states, that active merchant never stores the credit card owner - is there a way to fix that by the active merchant team?

**Comment by girasquid** [comment]
It looks like their documentation is [here](https://developers.paymill.com/en/reference/api-reference/) - I haven't read through it yet, but you could always submit a pull request.

**Comment by ntalbott** [comment]
@jungbunzlav we'd definitely review and merge a PR that fixes this. Thanks!
