### ISSUE TITLE
Feature: Adding support for simplify payment gate

### ISSUE THREAD

**Issue by leckylao** [Shopify/active_merchant#1551]
Hi,

I've started a branch to work on supports for https://www.simplify.com/commerce payment gateway. Now just had the purchase working. It's still in WIP. Creating the issue in order to reduce duplicate work and putting things together :smile:

**Comment by ntalbott** [comment]
@leckylao thanks for letting us know, but we prefer to not clutter up the Issue tracker with WIP. We'll be here when your PR is ready :grin:.
