### ISSUE TITLE
Changed format of authorization parameter in case of authorize.net

### ISSUE THREAD

**Issue by anujaware** [Shopify/active_merchant#1559]
Previously in response we were sending only transaction_id as a value in authorization parameter.  It has been changed to authorization = transaction_id#account_number in case of Athorize.net in latest version.

Why is it so? Can we revert it back to old one?

Code snippet from gem (File: https://github.com/Shopify/active_merchant/blob/master/lib/active_merchant/billing/gateways/authorize_net.rb)

    def commit(action, &payload)
      ...
      Response.new(
        ...
        authorization: authorization_from(response),
        ...
      )
      ... 
    end

    def authorization_from(response)
      [response[:transaction_id], response[:account_number]].join("#")
    end

**Comment by ntalbott** [comment]
@anujaware it changed so that the `Response#authorization` contains all the parts necessary to do ongoing/reference transactions. `#authorization` is intended for use in reference transactions; if you need one field specifically, you should pull it out of the `Response#params` instead.

**Comment by anujaware** [comment]
@ntalbott Thank you for quick response..!! Yes we are now using it from params.
