### ISSUE TITLE
SSLv3 error

### ISSUE THREAD

**Issue by sjf-control** [Shopify/active_merchant#1565]
I am getting an error message when attempting to place a credit card purchase. The error I'm getting is, "Exception Caught: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed", and the transaction is not completed.

According to the CC processor, the error is because they don't allow SSLv3 connections due to vulnerabilities. 

I am running an older version, 1.28.0, but I'm having problems upgrading due to a dependency issue.

1) Would upgrading resolve the issue?

2) Is there a way to restrict which SSL protocols are used by active_merchant when communicating with the gateway?

The processor says they currently support TLS 1.2, TLS 1.1, and TLS 1.0 with SHA256.
I did disable SSLv3 in the apache server, but the problem persists. 

I recognize that this may not be a problem with active_merchant itself. Getting pointed in the right direction would help.

Thanks for any help.

**Comment by ntalbott** [comment]
What gateway? What version of Ruby?

**Comment by sjf-control** [comment]
Gateway: AuthorizeNetGateway
Ruby: ruby 1.9.3p194 (2012-04-20 revision 35410) [i686-linux]
Rails: 3.2.11
OS: Ubuntu 12.04.5 LTS (production system)

Note that my CC processor is eProcessingNetwork.com running an Authorize.Net emulator for the gateway.

Strangely, while both my test and production gateway accounts fail on the production system. On my development system (OS X 10.10.2) I can process a transaction to the test account (haven't tried a real transaction on the development machine).  This leads me to believe there is some configuration setting somewhere that is different between the environments with whatever active_merchant is using to initialize the communications to the gateway.. 

Thanks for the assistance!

**Comment by sjf-control** [comment]
Any help?

**Comment by j-mutter** [comment]
Steven,
Unless [explicitly set](https://github.com/Shopify/active_merchant/blob/bae5e53b4d3e67ce239227382a9715cf05ea4457/lib/active_merchant/posts_data.rb#L8-L9) all connections via active_merchant gateways will use your system's 
default ssl settings. You will either need to hard-code your Authorize.net integration to use TLS or update your production environment. As you noticed, your development system is already configured correctly.

**Comment by sjf-control** [comment]
Thanks j-mutter, 

What specifically in the production environment needs updating? ActiveMerchant is the same version in both development and production (1.28.0). And all packages have been updated in the production Ubuntu 12.04.5 LTS OS. Are you saying I need to update to Ubuntu 14.04?  

BTW, the file you linked to "explicitly set" does not appear to exist in my ActiveMerchant gem 1.28.0

**Comment by girasquid** [comment]
You're going to want to upgrade your production system to at least Ruby 2.1.4 - [here](https://www.masteringmodernpayments.com/blog/stripe-ruby-sslv3-deprecated) is a pretty good looking blog post about doing that or other upgrades on your systems to handle the change.

The ability to explicitly choose SSL settings for your gateway was added to ActiveUtils in 2013, and ported from there into ActiveMerchant about a month ago; your version is a year older than the ActiveUtils addition, which is why that won't work for you. I would recommend upgrading, if possible.

**Comment by wmakley** [comment]
Hi guys, I have the same issue as sjf-control - Upgrading is basically not an option on this site for financial reasons (we are stuck with Ruby 1.8 as upgrading to Rails 3+ would be a massive undertaking), and I just need activemerchant (also a very old version) to stop using SSLv3. Is upgrading really the only way?

**Comment by ntalbott** [comment]
@wmakley it's the only supported way; you can of course try other approaches, but you'll be on your own.

**Comment by wmakley** [comment]
For the record, upgrading to activemerchant v1.43.3 on the Rails 2 sites I am dealing with seems to have resolved the issue, at least enough to permit customer checkout. The problem is (prepare to be terrified) Rails 1.2.6.
