### ISSUE TITLE
How to void a transaction?

### ISSUE THREAD

**Issue by rajeshlmindfiresolutions** [Shopify/active_merchant#1590]
How to void a transaction?

Always voiding a transaction showing error invalid transaction id with a valid data .

**Comment by girasquid** [comment]
This bug report doesn't give us a lot to go on.

Please tell us:
1) What gateway you're working with
2) How you got the transaction ID you're trying to void
3) What kind of transaction you're trying to void

Until then, there's not much we can do here.

**Comment by rajeshlmindfiresolutions** [comment]
1:   ACTIVE_GATEWAY = ActiveMerchant::Billing::PaypalExpressGateway.new({:login => ACTIVEMERCHANT_CONFIG[:username],  :password => ACTIVEMERCHANT_CONFIG[:password], :signature => ACTIVEMERCHANT_CONFIG[:signature]})

2: The transaction id we get from ACTIVE_GATEWAY.purchase method for a transaction  with a test environment.

3 . We are voiding through the void method . ACTIVE_GATEWAY.void(transaction_id) .

These are the procedure we are following to void a transaction. 

Please let us know if anything wrong . Thanks
