### ISSUE TITLE
How can we void a transaction?

### ISSUE THREAD

**Issue by rajeshlmindfiresolutions** [Shopify/active_merchant#1595]
How can we void a transaction?

1:   ACTIVE_GATEWAY = ActiveMerchant::Billing::PaypalExpressGateway.new({:login => ACTIVEMERCHANT_CONFIG[:username],  :password => ACTIVEMERCHANT_CONFIG[:password], :signature => ACTIVEMERCHANT_CONFIG[:signature]})

2: The transaction id we get from ACTIVE_GATEWAY.purchase method for a transaction  with a test environment.

3 . We are voiding through the void method . ACTIVE_GATEWAY.void(transaction_id) .

These are the procedure we are following to void a transaction. 

Always voiding a transaction showing error invalid transaction id with a valid data .

Please let us know if anything wrong . Thanks

**Comment by girasquid** [comment]
Most gateways only support voiding authorizations - if it's a purchase you'll want to refund it instead. Give that a try and re-open this if you're still having problems.
