### ISSUE TITLE
linkpoint no longer used by FirstData

### ISSUE THREAD

**Issue by westlakem** [Shopify/active_merchant#1604]
LinkPoint is no longer used by FirstData (can be seen by going to http://www.firstdata.com/linkpoint/)  They instead are using payeezy for ecommerce solutions (https://www.firstdata.com/en_us/products/merchants/ecommerce/payeezy-ecommerce-solution.html)  In order to continue use FirstData solutions, we need payeezy integrated and there's already a gem for it (https://github.com/payeezy/payeezy_ruby).

**Comment by ntalbott** [comment]
@westlakem while Linkpoint is no longer provisioned for new merchants, it continues to be used by many, so ActiveMerchant will continue to support it.

Adding support for Payeezy would be great, but it would be a new adapter buildout. If you get a chance to do that, be aware that ActiveMerchant does not allow using third party gems - the adapter should be built using ActiveMerchant's existing code and patterns, with no new dependencies.

If you submit a PR, we'd be happy to review it for merging. Thanks!
