### ISSUE TITLE
Remote tests

### ISSUE THREAD

**Issue by westlakem** [Shopify/active_merchant#1610]
As I was working on adding a new payment gateway, I was running "all" remote tests.  The results were as follows:

1922 tests, 5009 assertions, 748 failures, 268 errors, 0 pendings, 0 omissions, 5 notifications
47.1384% passed

The Unit tests looked good
2425 tests, 11112 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

but the remote tests need work.

**Comment by ntalbott** [comment]
@westlakem we would love it if all remote tests were run regularly, but many of them require private credentials, and so they don't get run, and will fail if you try to run them unless you have the right credentials in your local fixtures file.

If you want to go through and try to fix 'em, more power to you. That said, this is not actual a defect, and is expected as of today.
