### ISSUE TITLE
SSLv3

### ISSUE THREAD

**Issue by Orbycius** [Shopify/active_merchant#1623]
Hi folks

We're getting the following error:

    OpenSSL::SSL::SSLError (certificate verify failed):
      /usr/lib/ruby/1.8/net/http.rb:586:in `connect'
      /usr/lib/ruby/1.8/net/http.rb:586:in `connect'
      /usr/lib/ruby/1.8/net/http.rb:553:in `do_start'
      /usr/lib/ruby/1.8/net/http.rb:542:in `start'
      /usr/lib/ruby/1.8/net/http.rb:1035:in `request'
      /usr/lib/ruby/1.8/net/http.rb:845:in `post'
      lib/server/post_connection.rb:13:in `commit'

We're using an older version of `ActiveMerchant (Version 1.5.1 (February 14, 2010)` which has worked fine for years. However, on 12th March 2015 (last Thursday) it stopped working against SagePay, our payment gateway. 

Digging deeper, we see that SagePay turned off SSLv3 in favour of TLS back in February. Could this be causing the above error?

**Comment by j-mutter** [comment]
Yep, that sounds like the culprit. :+1:

**Comment by tobinharris** [comment]
Thanks @j-mutter. Can this be fixed at server level or is it a code fix?

**Comment by ntalbott** [comment]
@tobinharris it probably has more to do with your version of Ruby than it does with ActiveMerchant, though you'll probably have to upgrade them in tandem. It's possible you may be able to fix it in the code by forcing TLS in the adapter, but you'd have to experiment with that directly, as the maintainers aren't up on what works and what doesn't there.

**Comment by tobinharris** [comment]
Many thanks @ntalbott. We've just started support for a Rails 2.x solution on Ruby 1.8.x so it looks like we have our work cut out for us.

I did see the adapter monkey patch which we can try. Otherwise it's a full on Ruby update + Rails upgrade (which wouldn't be a bad move)

Thanks for your help.

**Comment by pollingj** [comment]
Just in case anyone is interested, I've managed to resolve this issue.  I was on ActiveMerchant 1.4.1.  The key seems to be taking the latest Certs from the master branch and putting the them into the version you are using.  

I had to make some other minor tweaks, but I think that's just due to me messing around with upgrading to Ruby 1.9.3.  I believe you should be able to stay on Ruby 1.8.7.

I think it might be worthwhile sticking the solution in the ReadMe, as I think there will be a number of people affected by this.

**Comment by Orbycius** [comment]
Thanks @pollingj is it just the cacert.pem in the lib/certs folder?

**Comment by pollingj** [comment]
@Orbycius yeah.  I did have to tweak some other things, but that was more to do with our setup, than ActiveMerchant.
