### ISSUE TITLE
Support for Encrypted Card Readers

### ISSUE THREAD

**Issue by jivamatic** [Shopify/active_merchant#1625]
Would be great for the ActiveMerchant library to support extra fields for Encrypted Card Readers. Authorize.net would be great to begin with since so many other gateways support the Authorize.net signatures. Looks like this would need the addition of a EncryptedTrackData field as an option during Purchase / Authorization.

Has this been considered in the past?

**Comment by ksondere** [comment]
@ntalbott, long time no see, wondered what your thoughts were on this.

**Comment by j-mutter** [comment]
[`CreditCard`](https://github.com/Shopify/active_merchant/blob/master/lib/active_merchant/billing/credit_card.rb#L136-L139) already supports track data :)

**Comment by j-mutter** [comment]
And the [`AuthorizeNetGateway `](https://github.com/Shopify/active_merchant/blob/master/lib/active_merchant/billing/gateways/authorize_net.rb#L229-L231) already handles it

**Comment by ntalbott** [comment]
@j-mutter I think what they're looking for is encrypted track data, i.e. straight off the card reader, pre-decryption.

That said, I don't know much at all about track data encryption, so not going to be much/any help here.

**Comment by andrewpaliga** [comment]
I believe Network Merchants already supports this: https://github.com/Shopify/active_merchant/blob/master/lib/active_merchant/billing/gateways/network_merchants.rb#L144

**Comment by jivamatic** [comment]
@j-mutter , Yes we are looking to send encrypted data directly. 

For ease of payment compliance the payment gateways issue a credit card reader that encrypts card information as its read. The decryption key is only available to the payment gateway. The encrypted blob needs to be passed to gateway. We need a way to embed that information into ActiveMerchant calls. Suspect the ActiveMerchant Authorize implementation needs to allow an extra XML tag or extra set of attributes to allow for this information to be passed.

**Some Authorize.net specific information if you are interested.**
The way Authorize.net supports this is by supporting an extra tag within the payment. Here is a [link](http://www.authorize.net/support/AIM_guide_XML.pdf#page=85). 

Here is the what the EncryptedTrackData tag looks like in Authorize.net

```xml
<encryptedTrackData>
<FormOfPayment>
<Value>
<Encoding>Hex</Encoding>
<EncryptionAlgorithm>TDES</EncryptionAlgorithm>
<Scheme>
<DUKPT>
<Operation>DECRYPT</Operation>
<Mode>
    <Data>1</Data>
<Mode>
<DeviceInfo>
<Description>
4649443D4944544543482E556E694D61672E416E64726F69642E53646B
76315e536f6d655442444b6579313d736f6d656f7468657276616c756
</Description>
</DeviceInfo>
<EncryptedData>
<Value>LongHexString</Value>
</EncryptedData>
</DUKPT>
</Scheme>
</Value>
</FormOfPayment>
</encryptedTrackData>
```

**Comment by brianmc** [comment]
Brian from Authorize.Net here, I think @jivamatic is spot-on and it should just be a case of adding the appropriate attributes.  We're happy to help out with any Anet or Encrypted data specific issues.

**Comment by louiskearns** [comment]
@brianmc, @jivamatic, go ahead and submit a PR  including tests, using the [network_merchants](https://github.com/Shopify/active_merchant/blob/master/lib/active_merchant/billing/gateways/network_merchants.rb#L144) example as reference.

**Comment by girasquid** [comment]
A PR for this would be awesome. :)
