### ISSUE TITLE
Does it support certificates using the SHA-256 algorithm ?

### ISSUE THREAD

**Issue by Debadatta** [Shopify/active_merchant#1628]
Hi 
We are using Ruby 2.1.2p95, rails 4.1.1, activemerchant 1.47.0 . 

We got the info for 2015-2016 SSL Certificate Change Microsite , https://ppmts.custhelp.com/app/answers/detail/a_id/1236 

It basically describes Updating integration to support certificates using the SHA-256 algorithm .

PayPal is upgrading SSL certificates on www.paypal.com per the following timeline.

Please note that the following dates are subject to change. We recommend that you check back for updates.

March 23, 2015

    www.paypal.com (intermediate change)

September 30, 2015

    www.paypal.com (SHA-256)

Can you please suggest will the same activemerchant(1.47.0) work for all time or we need to do any changes ?

Thanks

**Comment by noctivityinc** [comment]
+1

**Comment by girasquid** [comment]
ActiveMerchant itself won’t cause any issues with these PayPal changes, or with any SHA-2/SHA-256 certificates in general.  This is all handled by your SSL library, which is usually OpenSSL.  So long as your OpenSSL can connect successfully, ActiveMerchant will work just fine.

To test if your OpenSSL can support these changes, you can run the following command: `openssl s_client -connect www.sandbox.paypal.com:443`. If this works, you should see a successfully-negotiated TLS session, and ActiveMerchant will work just fine.

**Comment by anusha-nyros** [comment]
@girasquid When I type that command `openssl s_client -connect www.sandbox.paypal.com:443` in the root path of my heroku rails application I got a big message and at the end it is returning me the message like this: 

`SSL-Session:`
   ` Protocol  : TLSv1.2`
    `Cipher    : ECDHE-RSA-AES256-GCM-SHA384`
   ` Session-ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`
    `Session-ID-ctx: `
   ` Master-Key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`
    `Key-Arg   : None`
    `PSK identity: None`
  ` PSK identity hint: None`
   ` SRP username: None`
    `Start Time: 1433477863`
    `Timeout   : 300 (sec)`
    `Verify return code: 20 (unable to get local issuer certificate)`

 Is this going to be any problem to my paypal/ssl integration in my application? Please help me.

**Comment by galetahub** [comment]
Just add option CApath:
``` bash
openssl s_client -CApath /etc/ssl/certs/ -connect www.sandbox.paypal.com:443
```
