### ISSUE TITLE
Already initialized...

### ISSUE THREAD

**Issue by binarylogic** [Shopify/active_merchant#1630]
We recently upgraded ActiveMerchant. Every time we load our environments we see:

    lib/active_merchant/connection.rb:10: warning: already initialized constant MAX_RETRIES

As well as any other constant in that file. Is there something else we should be doing to avoid this? Thanks.

**Comment by ntalbott** [comment]
Are you also using offsite_payments, active_shipping, or another Shopify-created gem? You may have one of those that needs upgrading.

And are you on the latest ActiveMerchant?

**Comment by binarylogic** [comment]
Yep, we're using active_shipping which is one 0.12.5, and activemerchant which is on 1.47.0. We're on the latest versions for most of our gems.

**Comment by wvanbergen** [comment]
You'll need to upgrade to ActiveShipping >= 1.0 to resolve this.

**Comment by binarylogic** [comment]
Thanks, didn't see it as it's on 'pre' releases.

**Comment by wvanbergen** [comment]
Ah yes, we still haven't made a final release of that. Let me bug some people to make that happen.
