### ISSUE TITLE
Downloading subscriptions from CyberSource

### ISSUE THREAD

**Issue by dmitrypol** [Shopify/active_merchant#1631]
I am using active_merchant/billing/gateways/cyber_source.rb to do regular payments but we need to add subscriptions.  I see that the class supports creating subscriptions but how the heck do I query their API to download future transactions?

**Comment by girasquid** [comment]
ActiveMerchant doesn't expose anything for querying future transactions; that's something that you're going to have to write custom for your CyberSource integration.

**Comment by ntalbott** [comment]
Yup, and just so you don't get surprised, the recurring functionality in the Cybersource adapter is deprecated and will be removed altogether in the near future.
