### ISSUE TITLE
invalid multibyte char (US-ASCII) error in older version of Gem

### ISSUE THREAD

**Issue by bgadoury** [Shopify/active_merchant#1644]
I'm getting a very old Rails 2.3.18 app running again on Ruby 1.9.3 with ActiveMerchant 1.4.0, and I'm getting the "invalid multibyte char (US-ASCII)" error. 

I'm not clear how to resolve this issue given that the non ascii characters live in this gem. I believe this app was running OK with this same version of this gem OK on Ruby 1.8.7. Any advice? I'd like to get tis app running now on this version of the gem before I update it at all and risk breaking something elsewhere in the app. Any advice?

**Comment by j-mutter** [comment]
Hey @bgadoury,
Unfortunately we're not going to be much help here, as ActiveMerchant now only supports Rails 3.2+ and Ruby 2.0+. Ruby 1.9.3 is also [no longer supported at all](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/).

I know it can be a daunting task, but I would suggest updating your app to a newer version of Rails and Ruby if at all possible. 

Of course, you're free to use whatever versions you would like, however you're going to be on your own for the most part. If you absolutely cannot update, your best bet may be to fork ActiveMerchant and remove/replace the offending characters if possible, or add `encoding` comments to the files in question.

Best of luck!

**Comment by bgadoury** [comment]
We're definitely in a transition period right now and are aware of the delicate position we're in, but I totally agree. Thanks for the reply.
