### ISSUE TITLE
Anyone working on Stripe Connect changes?

### ISSUE THREAD

**Issue by cwise** [Shopify/active_merchant#1647]
Specifically, is anyone working on the changes to support Stripe Connect and payments with managed accounts.

This would be the following fields: 
* `destination`
* `application_fee`

If no one is already working on it, I can do so.

**Comment by ntalbott** [comment]
I believe `application_fee` is already supported (https://github.com/Shopify/active_merchant/blob/0726f8ffb273f76ef43e0a47cf520b51c9d929ff/lib/active_merchant/billing/gateways/stripe.rb#L246), but as far as I know no one is working on `destination`, so it's all yours

**Comment by cwise** [comment]
My bad - I actually remember seeing application_fee there last week. I'll work on destination.

**Comment by louiskearns** [comment]
cc @mhashemi86 @girasquid

**Comment by dprabu17** [comment]
please let me know how to setup stripe connected account?

**Comment by cwise** [comment]
> please let me know how to setup stripe connected account?

Feel free to email me with any specific questions.
