### ISSUE TITLE
PayGateXML Notify URL

### ISSUE THREAD

**Issue by bradly-swart** [Shopify/active_merchant#1652]
Hi,

I'm using the PayGate gateway, I've been processing transactions successfully but now I am receiving notify url errors, specifically:

{"ecode"=>"101", "edesc"=>"Notify URL Required For Authenticated Transaction"}

Having a look at the source file for this gateway there is a section at the bottom that describes the nurl option, but says its not used in this implementation, snippet bellow;

' others -- not used in this implementation
' nurl, rurl - must remain blank or absent or they will use an alternative authentication mechanism

I obviously now need this param to be parsed, is there a quick way to just enable it ?
I'm really stuck in a pinch here with a live system and customers not being able to make payments.

Thank you.

**Comment by bradly-swart** [comment]
I guess no one looks at this repo anymore.

**Comment by ntalbott** [comment]
@bradly-swart well, most of us have day jobs...

This sounds like something has changed in your configuration at PayGate (either by you or by them). You should contact them to ask why this parameter is now required whereas it wasn't before.

**Comment by bradly-swart** [comment]
Cheers Nathaniel.

Still not sure about getting these params usable in the options. I guess
I'll fork and figure it out.

Bradly Swart

Skype: bradly.swart
Twitter: @brad8711 <http://twitter.com/brad8711>
linkedIn: http://linkedin.com/in/bradlyswart

**Comment by ntalbott** [comment]
@bradly-swart I guess my point is, you should not need to use the params with ActiveMerchant, nor am I even sure it will be possible to do so. I'm pretty sure the config on your backing account at PayGate has been borked, and that this issue is not at the ActiveMerchant level.
