### ISSUE TITLE
Stripe remote tests are failing

### ISSUE THREAD

**Issue by ntalbott** [Shopify/active_merchant#1664]
```
ntalbott@lorica:~/src/active_merchant$ ruby -Itest test/remote/gateways/remote_stripe_test.rb
```

:boom:

```
Finished in 41.677674 seconds.
--------------------------------------------------------------------------------
50 tests, 200 assertions, 16 failures, 2 errors, 0 pendings, 0 omissions, 0 notifications
64% passed
--------------------------------------------------------------------------------
1.20 tests/s, 4.80 assertions/s
```

16 failures seems pretty bad; are the Stripe tests passing for @Shopify/active-merchant peeps?

**Comment by girasquid** [comment]
It looks like all of the EMV/applepay remotes fail - @jnormore / @bizla ?

**Comment by bizla** [comment]
The EMV APIs haven't been deployed to production merchant accounts yet, so those will continue to fail publicly, but the EMV test cases are passing here. Maybe I should add `skip`s to those testcases until they can be green for everyone.

**Comment by duff** [comment]
@bizla It would be excellent if they could get to a running state.  We're having an issue with a customer's customer whose Stripe account version has changed making a field (`statement_description`) no longer valid.  Having a green suite of remote tests for Stripe would really help with our possible version adjustments to ensure we're not breaking anything.  Thanks!

**Comment by bizla** [comment]
Apple Pay is tricky because the Apple Pay token has to be generated with an iPhone 6 containing the certificate [associated to your test account](https://stripe.com/docs/mobile/apple-pay). Are you folks okay with running the Apple Pay remote tests? For now, I have a branch that omits the EMV testcases on account of that API not being widely available yet. Apple Pay currently is, though.

**Comment by jnormore** [comment]
Apple pay remote won't work, stripe doesn't have the concept of an apple pay test

**Comment by duff** [comment]
@bizla Would putting the credentials for your stripe account in `fixtures.yml` help?  Then perhaps the remote tests for apple pay could work if your test account is setup for that.  We're sharing credentials for other sandboxes so I wouldn't imagine there'd be an issue with adding a Stripe sandbox to fixtures.

**Comment by bizla** [comment]
No, unfortunately. The Apple Pay tokens generated in-app only have lifetimes of 24 hours IIRC, so the way we'd test internally is to generate a token through an iPhone 6, then fire it through our test account (where we've successfully done the Apple CSR dance.) So, S=similar to those Stripe tests that fail by default if you're not using Stripe Connect setup, the Apple Pay tests live there for you to run given the right testbed. 
Stay tuned for the PR that omits the EMV remote tests though -- in retrospect, it didn't make sense to add those to the suite until the APIs are actually live for all production merchant IDs.

**Comment by duff** [comment]
Sounds good @bizla.  Do you think the Apple pay remote tests could be omitted too?  Then when someone wants to do the "generate token on an iPhone6" dance, then can do so and temporarily make them not omitted.

Or maybe there could be a separate stripe apple pay remote test file for those interested.  Then there wouldn't be a hacky omit / not omit cycle to run apple pay remote tests.  And we'd get back to the state of having a green bar for Stripe remote tests.

Thanks for all your help sorting this out!

**Comment by bizla** [comment]
Yeah, Apple Pay and EMV are fairly specific so I'm cool with extracting them into their own test files. I'll get a PR in to do this.

**Comment by duff** [comment]
@bizla, @jnormore, @girasquid, and @ntalbott,

I created a PR -> https://github.com/Shopify/active_merchant/pull/1676 for this in an attempt to do what we discussed here.  Does it look reasonable?

**Comment by girasquid** [comment]
:+1: from me - thanks for doing this!
