### ISSUE TITLE
Link to API Documentation from README.md is broken

### ISSUE THREAD

**Issue by rakvium** [Shopify/active_merchant#1716]
Click on "API documentation" link from README.md leads to
http://www.rubydoc.info/github/Shopify/active_merchant/master/file/README.md
and returns 404 Not Found page with text:
> Sorry, but we couldn't find the page /github/Shopify/active_merchant/master/file/README.md in the Shopify/active_merchant GitHub repository. Are you sure that class, method, or file exists?

**Comment by girasquid** [comment]
Updated - thanks!

**Comment by rakvium** [comment]
Thank you for the fast feedback :construction_worker:
