### ISSUE TITLE
ARB functionality in ActiveMerchant is deprecated and will be removed in a future version

### ISSUE THREAD

**Issue by JulienDefrance** [Shopify/active_merchant#1718]
Just noticed the following while utilizing the last version of your gem:
"ARB functionality in ActiveMerchant is deprecated and will be removed in a future version. Please contact the ActiveMerchant maintainers if you have an interest in taking ownership of a separate gem that continues support for it."

How are you expecting to support recurring billing if you get rid of this functionality?
Will you ultimately remove the entire AuthorizeNetArbGateway class?
Unless you have an alternative, Is there an actual reason for doing so, or could you just keep it there for people to use if they still want to?

**Comment by girasquid** [comment]
Hi Julien,

See the discussion at https://github.com/Shopify/active_merchant/pull/1178
for more details.

Luke
