### ISSUE TITLE
AutorizeNetCimGateway: transaction id= 0 in test mode

### ISSUE THREAD

**Issue by ashutosh413** [Shopify/active_merchant#1719]
When I am using AuthorizeNetGateway i am getting transaction id starting with 2 which is correct. But when i am using AuthorizeNetCimGateway with same settings as for AuthorizeNetGateway, I am getting transaction id = 0 for every transaction. why so?

**Comment by ntalbott** [comment]
@ashutosh413 I have no idea what you're talking about. You'll have to provide a lot more specifics - preferably code, example responses, etc. - for us to be able to help you.

**Comment by ashutosh413** [comment]
activemerchant_mode: test
authorize_net_login: 5qD4tG9Y
authorize_net_password: 5eZ8h4V4gKHgJ78p

ActiveMerchant::Billing::Base.mode = ENV['activemerchant_mode'].to_sym

GATEWAY = ActiveMerchant::Billing::AuthorizeNetCimGateway.new(:login => ENV['authorize_net_login'], :password => ENV['authorize_net_password'])


############TRANSACTION######################################################
amount= 210
transaction_options = { transaction: { type: :auth_capture, amount: amount,	customer_profile_id: customer_profile_id, customer_payment_profile_id: customer_payment_profile_id }}

transaction_response = GATEWAY.create_customer_profile_transaction(transaction_options)

###############################################################################


####################RESPONSE#################################################
<ActiveMerchant::Billing::Response:0xe6cadd @fraud_review=nil, @message="Successful.", @authorization="0", @test=true, @params={"messages"=
>{"result_code"=>"Ok", "message"=>{"code"=>"I00001", "text"=>"Successful."}}, "direct_response"=>{"raw"=>"1,1,1,(TESTMODE) This transaction has been approved.,000000,P,0,,,210.00,CC,auth_capture,,,,,,
,,,,,,atiflarz@gmail.com,,,,,,,,,,,,,,BFA7A766AA8EB0FC01820372358119FE,,,,,,,,,,,,,XXXX4444,MasterCard,,,,,,,,,,,,,,,,", "response_code"=>"1", "response_subcode"=>"1", "response_reason_code"=>"1", "me
ssage"=>"(TESTMODE) This transaction has been approved.", "approval_code"=>"000000", "avs_response"=>"P", "transaction_id"=>"0", "invoice_number"=>"", "order_description"=>"", "amount"=>"210.00", "met
hod"=>"CC", "transaction_type"=>"auth_capture", "customer_id"=>"", "first_name"=>"", "last_name"=>"", "company"=>"", "address"=>"", "city"=>"", "state"=>"", "zip_code"=>"", "country"=>"", "phone"=>"",
 "fax"=>"", "email_address"=>"atiflarz@gmail.com", "ship_to_first_name"=>"", "ship_to_last_name"=>"", "ship_to_company"=>"", "ship_to_address"=>"", "ship_to_city"=>"", "ship_to_state"=>"", "ship_to_zi
p_code"=>"", "ship_to_country"=>"", "tax"=>"", "duty"=>"", "freight"=>"", "tax_exempt"=>"", "purchase_order_number"=>"", "md5_hash"=>"BFA7A766AA8EB0FC01820372358119FE", "card_code"=>"", "cardholder_au
thentication_verification_response"=>"", "account_number"=>"XXXX4444", "card_type"=>"MasterCard", "split_tender_id"=>"", "requested_amount"=>"", "balance_on_card"=>""}}, @avs_result={"code"=>nil, "mes
sage"=>nil, "street_match"=>nil, "postal_match"=>nil}, @cvv_result={"code"=>nil, "message"=>nil}, @success=true>
###############################################################################

**Comment by ashutosh413** [comment]
please check the transaction id in above response.

**Comment by ntalbott** [comment]
@ashutosh413 that's an Authorize.Net returned field, and outside the scope of ActiveMerchant. You'll need to take it up with Auth.Net.
