### ISSUE TITLE
authorize.net: ability not to send x_currency_code

### ISSUE THREAD

**Issue by wedy** [Shopify/active_merchant#1726]
what i'd like to do here,  i don't want to pass `x_currency_code`, instead i'd like to control the currency from my Authorize.net account and currency settings on it.
so i think it shouldn't force people to use 'USD' as default_currency
perhaps change the `default_currency = nil`, what you guys think ? im happy to create a PR for this.

**Comment by ntalbott** [comment]
No plans to change it as a default, but can't you just change the default_currency in your local environment?

**Comment by wedy** [comment]
hi ntalbott, yeah true  it's a `class_attribute`, yeah i can change the value. thanks for your help
