### ISSUE TITLE
Paypal gateways & 3d secure

### ISSUE THREAD

**Issue by wedy** [Shopify/active_merchant#1746]
hi guys any thoughts to add 3d secure to paypal ? if not im more than happy to create a PR for this.

**Comment by ntalbott** [comment]
@wedy ActiveMerchant does not support 3DS flow; you'll need to implement it externally.

**Comment by wedy** [comment]
thanks @ntalbott, ah okay i saw ogone supports 3ds, i thought we could add 3ds into paypal soap field

we just need to pass these fields to paypal.
```
<ThreeDSecureRequest>
          <MpiVendor3ds>Y</MpiVendor3ds>
          <AuthStatus3ds>Y</AuthStatus3ds>
          <Cavv>jMKEKlqlJGiJARAbxMDZ5+fnFeg=</Cavv>
          <Eci3ds>02</Eci3ds>
          <Xid>TTVmdlFxbERYVXo5R1hrVUY5bjY=</Xid>
        </ThreeDSecureRequest>
```
ref:  https://developer.paypal.com/docs/classic/paypal-payments-pro/integration-guide/ThreeDSecure/

Ogone code in Active Merchant:
https://github.com/Shopify/active_merchant/blob/master/lib/active_merchant/billing/gateways/ogone.rb

thanks

**Comment by ntalbott** [comment]
@wedy Ogone non-AM standard 3DS support slid in before we started enforcing what is and what isn't a fit for AM; that functionality should really be deprecated.

I'd be happy to add 3d-secure specific fields to the `options` hash to be passed through on the existing/standard AM calls. But most 3DS processes involve multiple calls to complete what AM does in a single call (purchase, authorize), and we don't support making those extra calls or modifying the existing calls in ways that affect non-3DS processing.

If you want to submit a PR adding fields to `options` and pushing them through into the XML, I'd be happy to consider it for inclusion.

**Comment by wedy** [comment]
thank @ntalbott , yeah understood - ill add those additional fields into the `options` hash
appreciate your prompt reply
