### ISSUE TITLE
This is getting out of hand

### ISSUE THREAD

**Issue by yazinsai** [Shopify/active_merchant#1749]
#1563 has been pending addition for over 4 months now. I realize you guys are busy, but this is getting a tad out of hand.. and there are over 40 PRs open.

How can we help?

**Comment by ntalbott** [comment]
@yazinsai feel free to dig into the project, read a lot of code, learn the style, and start providing initial triage comments on PR's. If you show that you can identify what code's a good fit for the project or not, what changes need to be made for a PR to get accepted, and are long term committed to contributing to ActiveMerchant, we'd consider adding you as a maintainer. It'll take a while to prove yourself, though, so get ready to dig in for the long haul.

Hope this helps you understand how to start contributing!
